### ISSUE TITLE
How to get TS typings?

### ISSUE THREAD

**Issue by sergak01** [nodemailer/imapflow#1]
Hello!

In the readme file, you are talking about typing, but I did not find it.

> ImapFlow has TS typings set for compatible editors.

Can I get typings?

Thank you!

**Comment by andris9** [comment]
For now I disabled including typings file with imapflow as for some reason VSCode refused to pick it up while it worked really well detecting the types from JSDoc comments like show here:

<img width="642" alt="Screenshot 2020-01-28 at 09 18 04" src="https://user-images.githubusercontent.com/132242/73242988-1d026580-41af-11ea-950b-c2eeee02c982.png">

I used to generate typings file from JSDoc comments, you can try it out by running `npm run dst` in imapflow folder which should generate lib/types.d.ts

**Comment by sergak01** [comment]
#2 Send pull request

**Comment by andris9** [comment]
I published v1.0.5 with the typings file but did not use your PR

1. Typings file is not included in git intentionally as it is created by pre-publish script when publishing module to npm. If you install v1.0.5 you can find the types file from node_modules/imapflow/lib/types.d.ts (it is now also referenced from package.json file) even though the file is missing from git. If you need the file for development run `npm run dst`
2. I did not include EventEmitter definitions as imapflow seems wrong place for defining standard Node classes. Instead I enhanced the build script to inject node and EventEmitter references to the typings file.
3. I used the `@module` definition you had in your PR.

Could you check if it works for you? I do not use TypeScript myself, only tried to compile a simple test file using the following command and got no errors:

```
$ tsc --moduleResolution node -t ESNext test.ts
```

**Comment by sergak01** [comment]
Types work correctly for me.

Nice work!
