### ISSUE TITLE
Export types in package

### ISSUE THREAD

**Issue by rmccue** [nodemailer/imapflow#4]
Hi! I'm trying to build some functions which use return values from parts of imapflow, but the types aren't exported from the package.

It's possible to work around this with a bit of magic using the function return types:

```tsx
import { ImapFlow } from 'imapflow';

type PromiseResult<T> = T extends PromiseLike<infer U> ? U : T;
export type FetchMessageObject = PromiseResult<ReturnType<ImapFlow['fetchOne']>>;
```

Would it be possible to have the types exported directly?

**Comment by andris9** [comment]
Any suggestion of how to do it? I know almost nothing about TypeScript and only through some major type wrangling managed to set up the current automatic task that generates typings file from JSDoc comments. I certainly do not want to start managing the typings file by hand, it must be generated from JSDoc in a way or another.

**Comment by rmccue** [comment]
Seems like the problem is that the `declare` for the typedefs is emitted outside of the `declare module`; this may be related to https://github.com/englercj/tsd-jsdoc/issues/64

I think I've found an easier workaround (which isn't entirely clean, but which will work), which is to use a `<reference />` triple-slash directive directly to the types file:

```tsx
/// <reference path="./node_modules/imapflow/lib/types.d.ts"/>

// Types are now in-scope for this file, can be re-exported
export type Message = FetchMessageObject;
```

So, I think that's good enough for now; potentially it's something tsd-jsdoc needs to fix long-term though.

I'll close this out :)

**Comment by rmccue** [comment]
(Further quick note: the `<reference />` triple-slash directive actually imports the types into the global ("ambient") scope, so `FetchMessageObject` (eg) can be used anywhere in the project after that reference.)

**Comment by rmccue** [comment]
FYI, there's a bunch of issues with the generated types, so I've been using a local type override file instead. I'd suggest it's probably worth disabling the automatic generation entirely, as the types can then be managed via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by andris9** [comment]
Yeah, I agree, it seemed easier at first but as I do not use TypeScript myself it is impossible for me to understand if the autogenerated typings provide any value or make things worse. I'll remove the typings pointer from package.json in next release and keep the autogeneration around just for reference.

**Comment by georgyfarniev** [comment]
Hi @andris9, would you consider adding manually written types as part of library, if I have time to write them? Or do you think it better to add them to DefinitelyTyped?

**Comment by andris9** [comment]
@georgyfarniev  Rather add these to DefinitelyTyped.

**Comment by georgyfarniev** [comment]
@andris9 alright. Thanks for fast reply!

**Comment by danielgary** [comment]
The types in DefinitelyTyped are fantastic!

**Comment by TylerBarnes** [comment]
For what it's worth in 2023 the generated types are much better. The DefinitelyTyped types are wrong for many things. Not sure if this is because those types are now out of date or if they were always partially wrong.

 `/// <reference path="../../../node_modules/imapflow/lib/types.d.ts"/>` is the way to go since it's mostly correct.

I'll try to see if I can find some time to fix the definitely typed types and make a PR there.
