### ISSUE TITLE
More permissive license?

### ISSUE THREAD

**Issue by rlitman-10c** [nodemailer/imapflow#6]
Would you consider changing the license to something more permissive like MIT (which is used by nodemailer) or BSD or Apache or at least dual-licensing it (like Mozilla does)? AGPL is a no-go for most commercial projects.

**Comment by andris9** [comment]
ImapFlow module is part of [IMAP API](https://imapapi.com) and there is a commercial version license for IMAP API that also covers ImapFlow. For everything open source related AGPL should be OK.
